name: Deploy
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build frontend test image
        run: docker build -t 01042015/react-test -f ./client/Dockerfile.dev ./client
      - name: Run frontend tests
        run: docker run -e CI=true 01042015/react-test npm test

      - name: Build client production image
        run: docker build -t 01042015/multi-client -f ./client/Dockerfile ./client
      - name: Build server production image
        run: docker build -t 01042015/multi-server -f ./server/Dockerfile ./server
      - name: Build worker production image
        run: docker build -t 01042015/multi-worker -f ./worker/Dockerfile ./worker

      - name: Login into Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push production client image
        run: docker push 01042015/multi-client
      - name: Push production server image
        run: docker push 01042015/multi-server
      - name: Push production worker image
        run: docker push 01042015/multi-worker
        
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-205603051109
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
