name: Deploy
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build frontend test image
        run: docker build -t andrewssouza/react-test -f ./client/Dockerfile.dev ./client
      - name: Run frontend tests
        run: docker run -e CI=true andrewssouza/react-test npm test
